name: 'Islandora Starter Site'
description: 'Full Drupal Site configured for Islandora.'
type: 'Site Install'
install:
  - action
  - admin_toolbar
  - advanced_search
  - automated_cron
  - basic_auth
  - better_exposed_filters
  - big_pipe
  - block
  - block_content
  - breakpoint
  - citation_select
  - ckeditor5
  - coi
  - comment
  - config
  - config_override_core_fields
  - config_update
  - contact
  - context
  - context_ui
  - contextual
  - controlled_access_terms
  - controlled_access_terms_defaults
  - csv_serialization
  - ctools
  - datetime
  - dblog
  - devel
  - dgi_image_discovery
  - dynamic_page_cache
  - editor
  - eva
  - facets
  - facets_summary
  - field
  - field_group
  - field_permissions
  - field_report
  - field_ui
  - file
  - file_replace
  - filehash
  - filter
  - flysystem
  - fpa
  - geolocation
  - hal
  - help
  - history
  - image
  - islandora
  - islandora_audio
  - islandora_breadcrumbs
  - islandora_core_feature
  - islandora_fits
  - islandora_iiif
  - islandora_image
  - islandora_mirador
  - islandora_text_extraction
  - islandora_text_extraction_defaults
  - islandora_video
  - islandora_workbench_integration
  - jquery_ui
  - jquery_ui_autocomplete
  - jquery_ui_datepicker
  - jquery_ui_menu
  - jquery_ui_slider
  - jquery_ui_touch_punch
  - jsonld
  - jwt
  - key
  - language
  - link
  - matomo
  - media
  - menu_link_content
  - menu_ui
  - migrate
  - migrate_plus
  - migrate_source_csv
  - mysql
  - node
  - openseadragon
  - options
  - page_cache
  - path
  - path_alias
  - pdf
  - pgsql
  - prepopulate
  - rdf
  - responsive_image
  - rest
  - rest_oai_pmh
  - search_api
  - search_api_solr
  - serialization
  - shortcut
  - sqlite
  - syslog
  - system
  - taxonomy
  - taxonomy_manager
  - term_merge
  - term_reference_change
  - text
  - token
  - toolbar
  - tour
  - twig_tweak
  - update
  - user
  - views_data_export
  - views_field_view
  - views_nested_details
  - views_ui
  - content_translation
  - views
  - olivero
  - claro
config:
  actions:
    system.site:
      simple_config_update:
        page.front: /collections
        name: 'Islandora Recipes Starter Site'
    system.theme:
      simple_config_update:
        default: olivero
        admin: claro
    user.role.anonymous:
      grantPermissions:
        - 'access comments'
        - 'access content'
        - 'access site-wide contact form'
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'access comments'
        - 'access content'
        - 'access shortcuts'
        - 'access site-wide contact form'
        - 'opt-in or out of matomo tracking'
        - 'post comments'
        - 'skip comment approval'
        - 'view media'